Fix/login bugs
team-chocolate-cake/MovieApp pull request #128
Opened 2023-06-30 11:57 UTC by marwanm7moud

2023-06-30 16:05 UTC, mohammed-akkad commented on feature/authectication/presentation/ui/src/main/res/layout-land/fragment_login.xml
> +                android:padding="16dp"
use dimen

2023-06-30 16:05 UTC, mohammed-akkad commented on feature/authectication/presentation/ui/src/main/res/xml/fragment_login_xml_landscape_constraintlayout_scene.xml
> +            android:layout_marginTop="16dp"
use dimen

2023-06-30 16:06 UTC, mohammed-akkad reviewed
great work

2023-06-30 16:08 UTC, MohamedElgohary88 commented on feature/authectication/presentation/ui/src/main/res/layout/fragment_login.xml
>                  android:padding="16dp"
use dimens

2023-06-30 19:07 UTC, mosayed01 requested changes

2023-06-30 19:07 UTC, mosayed01 commented on feature/authectication/presentation/ui/src/main/res/xml/fragment_login_xml_landscape_constraintlayout_scene.xml
> +        motion:duration="1000">
300 is better

2023-06-30 19:07 UTC, mosayed01 commented on feature/authectication/presentation/ui/src/main/res/xml/fragment_login_xml_landscape_constraintlayout_scene.xml
> +
white space

2023-07-01 07:06 UTC, mosayed01 approved these changes

2023-07-01 12:17 UTC, merged